export const dataEverything = [
  {
    id: 1,
    icon: "icons/icon6.png",
    subject: "Real-Time Emotion Detection",
    description:
      "AI detects your facial expressions during practice and gives live emotion labels (Happy, Nervous, Neutral, Confident)",
  },
  {
    id: 2,
    icon: "icons/icon1.png",
    subject: "AI-Generated Answer Drafts",
    description:
      "Get structured answer suggestions using the STAR method tailored to each interview question",
  },
  {
    id: 3,
    icon: "icons/icon2.png",
    subject: "Session Recording & Replay",
    description:
      "Record your practice session and review your performance video afterward for self-evaluation",
  },
  {
    id: 4,
    icon: "icons/icon3.png",
    subject: "Progress Dashboard",
    description:
      "Track your confidence score, emotion trends, and improvement across multiple sessions in one visual dashboard",
  },
  {
    id: 5,
    icon: "icons/icon4.png",
    subject: "Curated Question Bank",
    description:
      "Practice with role-specific questions for Software Engineer, Data Analyst, Product Manager, and more",
  },
  {
    id: 6,
    icon: "icons/icon5.png",
    subject: "Motivational AI Feedback",
    description:
      "After each session, receive a personalized summary and motivational message generated by Gemini AI",
  },
];

export const dataHowItWorks = [
  {
    id: 1,
    step: "Step 1",
    title: "Create Your Profile",
    description:
      "Sign up and tell us your target role and industry. We'll personalize your question bank right away",
    image: "/hero/howcreate.png",
  },
  {
    id: 2,
    step: "Step 2",
    title: "Run a Simulation",
    description:
      "Start a timed mock interview. Our AI watches your expressions and gives real-time emotion feedback on screen",
    image: "/hero/howrun.png",
  },
  {
    id: 3,
    step: "Step 3",
    title: "Review & Improve",
    description:
      "After each session, get a full performance report, AI feedback, and your emotion trend chart",
    image: "/hero/howreview.png",
  },
];

export const testimonialData = [
  {
    id: 1,
    rating: 5,
    review:
      "I used to freeze during every interview. After 5 sessions on Intersight, I landed my first job offer. The emotion feedback was a game changer.",
    name: "Monica Dyah P.",
    role: "Fresh Graduate",
  },
  {
    id: 2,
    rating: 4,
    review:
      "The AI feedback helped me improve my confidence and speaking clarity. The simulations felt realistic and helpful.",
    name: "Zahwa Anissa H.",
    role: "Software Engineer",
  },
  {
    id: 3,
    rating: 4,
    review:
      "The emotion tracking caught that I looked nervous when discussing CSS — something I never noticed. Now I ace the \'tell me about your project\' questions with ease.",
    name: "Syasmi Permata Oktavia",
    role: "Front-End Developer",
  },
  {
    id: 4,
    rating: 5,
    review:
      "I practiced every night before my interview. The emotion tracking feature really improved my body language.",
    name: "Via Angelya",
    role: "UI/UX Designer",
  },
  {
    id: 5,
    rating: 5,
    review:
      "I used to blank out when asked about system design. After 7 sessions on Intersight, I confidently explained my architecture choices and got an offer as a Full-Stack Dev!",
    name: "Prasetyo Dio",
    role: "Full-Stack Developer",
  },
  {
    id: 6,
    rating: 5,
    review:
      "One of the best AI interview practice platforms I\'ve ever used. Highly recommended for fresh graduates.",
    name: "Aqilla Z. Fakhira",
    role: "Data Analyst",
  },
];

export const faqData = [
  {
    id: 1,
    question: "How does Intersight actually analyze my emotions?",
    answer:
      "Intersight uses AI-powered facial expression analysis during your mock interview sessions. The system detects emotional signals such as confidence, nervousness, focus, and engagement in real-time to help you improve your interview performance.",
  },
  {
    id: 2,
    question: "Does the platform record my voice or just my face?",
    answer:
      "Intersight can analyze both your facial expressions and voice interactions depending on the session settings. Your recordings are securely stored and used only for generating personalized interview feedback and performance reports.",
  },
  {
    id: 3,
    question: "Can I get feedback on the content of my answers?",
    answer:
      "Yes. Intersight provides AI-generated answer evaluations based on structure, clarity, communication style, and relevance using interview best practices such as the STAR method.",
  },
  {
    id: 4,
    question: "How accurate is the emotion detection?",
    answer:
      "Our AI emotion detection model is trained on advanced computer vision and facial recognition datasets to provide highly reliable emotional analysis. While no AI system is perfect, Intersight continuously improves its accuracy through machine learning optimization and real-world interview simulations.",
  },
];